### ISSUE TITLE
Is the example in the README correct?

### ISSUE THREAD

**Issue by AdamGagorik** [ScribeMD/rootless-docker#11]
I have tried the example in the README in a workflow.

```yaml
- name: Use Docker in rootless mode.
  uses: ScribeMD/rootless-docker@0
```

I observe the following error:

> Error: Unable to resolve action `ScribeMD/rootless-docker@0`, unable to find version `0`

**Comment by AdamGagorik** [comment]
Works if I am more explicit on the release tag.

```yaml
- name: Use Docker in rootless mode.
  uses: ScribeMD/rootless-docker@0.1.1
```

**Comment by Kurt-von-Laven** [comment]
@AdamGagorik, thank you for reporting this rather glaring issue. I misinterpreted GitHub's docs to suggest that GitHub Actions understands semantic versioning:

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work. ~ [`jobs.<job_id>.steps[*].uses
`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses)

However, if users want to be able to reference a major version, the action maintainer has to tag it themselves. I personally feel most users will benefit from pinning a specific version so that they don't need to worry about a dependency breaking them. [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) can automatically update these version numbers as often as desired, which seems safer than depending on a major version. I will update the README to show a specific version instead.

**Comment by Kurt-von-Laven** [comment]
github/docs#17776 was recently merged, clarifying the upstream documentation.
